# Generated by Django 3.2.18 on 2023-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('aborted', 'aborted')], default='in_progress', max_length=64)),
                ('reference_timestamp', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
