# Generated by Django 3.2.18 on 2023-04-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reports', '0002_restaurantreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('aborted', 'aborted')], default='in_progress', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantreports',
            name='consolidated_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_reports.consolidatedreport'),
            preserve_default=False,
        ),
    ]
