# Generated by Django 3.2.18 on 2023-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reports', '0003_auto_20230406_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantoperationtimeslots',
            name='store_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurantreports',
            name='store_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurantstatusdata',
            name='store_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='restauranttimezoneinfo',
            name='store_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
