# Generated by Django 4.2.10 on 2024-02-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reports', '0004_auto_20230406_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantoperationtimeslots',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='restaurantstatusdata',
            old_name='timestamp',
            new_name='timestamp_utc',
        ),
        migrations.RenameField(
            model_name='restauranttimezoneinfo',
            old_name='timezone',
            new_name='timezone_str',
        ),
    ]
