# Generated by Django 4.2.10 on 2024-02-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reports', '0005_rename_day_of_week_restaurantoperationtimeslots_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantoperationtimeslots',
            old_name='start_time',
            new_name='end_time_local',
        ),
        migrations.RenameField(
            model_name='restaurantoperationtimeslots',
            old_name='end_time',
            new_name='start_time_local',
        ),
    ]
